// ============================================================
// Warehouse / Inventory Mock Data
// ============================================================

export type ItemCategory = "MED" | "EQU" | "CON";

export interface WarehouseItem {
  id: string;
  code: string;
  name: string;
  description: string;
  quantity: number;
  minimumQuantity?: number;
  unit: string;
  category: ItemCategory;
}

export type TransactionType = "เพิ่มสินค้าใหม่" | "เติมสินค้า" | "เบิกสินค้า" | "นำออก";
export type ApprovalStatus = "รออนุมัติ" | "อนุมัติ" | "ไม่อนุมัติ";

export interface Transaction {
  id: string;
  code: string;
  type: TransactionType;
  itemCode: string;
  itemName: string;
  quantity: number;
  operator: string;
  date: string;
  approvalStatus: ApprovalStatus;
  approvedBy?: string;
  approvedAt?: string;
  rejectedBy?: string;
  rejectedAt?: string;
  rejectionReason?: string;
}

// ── Inventory Items ──────────────────────────────────────────
export const mockWarehouseItems: WarehouseItem[] = [
  {
    id: "1",
    code: "MED-001",
    name: "น้ำเกลือ 0.9%",
    description: "สารละลายโซเดียมคลอไรด์ 0.9% สำหรับล้าง...",
    quantity: 120,
    unit: "ขวด",
    category: "MED",
  },
  {
    id: "2",
    code: "MED-002",
    name: "น้ำตาลไร้ (น้ำปลอดเชื้อ)",
    description: "น้ำปราศจากเชื้อใช้สำหรับผสมและละลายอุปกรณ์",
    quantity: 100,
    unit: "ขวด",
    category: "MED",
  },
  {
    id: "3",
    code: "MED-003",
    name: "สายสวนปัสสาวะ",
    description: "สายสวนสำหรับระบายปัสสาวะสำหรับผู้ป่วย",
    quantity: 60,
    unit: "ชิ้น",
    category: "MED",
  },
  {
    id: "4",
    code: "MED-004",
    name: "อุปกรณ์ท่าแมค",
    description: "อุปกรณ์เสริมสำหรับดำเนินแพทย์มูลฐาน",
    quantity: 40,
    unit: "ชุด",
    category: "MED",
  },
  {
    id: "5",
    code: "MED-005",
    name: "ถุงมือแพทย์",
    description: "ถุงมือ สำหรับป้องกันการสัมผัสเชื้อโรค",
    quantity: 80,
    unit: "กล่อง",
    category: "MED",
  },
  {
    id: "6",
    code: "MED-006",
    name: "หน้ากากอนามัย",
    description: "หน้ากากป้องกันเชื้อโรค",
    quantity: 150,
    unit: "กล่อง",
    category: "MED",
  },
  {
    id: "7",
    code: "MED-007",
    name: "แอลกอฮอล์",
    description: "แอลกอฮอล์ฝาผอ ล้างมือ สำหรับทำความสะอาด",
    quantity: 50,
    unit: "ขวด",
    category: "MED",
  },
  {
    id: "8",
    code: "EQU-001",
    name: "ก๊อซ",
    description: "ก้อนซับเลือดและปิดแผล",
    quantity: 70,
    unit: "แพ็ค",
    category: "EQU",
  },
  {
    id: "9",
    code: "EQU-002",
    name: "คีม",
    description: "คีมสำหรับทำความสะอาดแผล",
    quantity: 60,
    unit: "แพ็ค",
    category: "EQU",
  },
  {
    id: "10",
    code: "EQU-003",
    name: "พลาสเตอร์ปิดแผล",
    description: "พลาสเตอร์สำหรับปิดแผลขนาดเล็ก",
    quantity: 40,
    unit: "กล่อง",
    category: "EQU",
  },
  {
    id: "11",
    code: "CON-001",
    name: "นม",
    description: "นมสำหรับผู้สูงอายุทุกกลุ่มผู้ป่วย",
    quantity: 200,
    unit: "กล่อง",
    category: "CON",
  },
  {
    id: "12",
    code: "CON-002",
    name: "แผ่นเฝือ",
    description: "ผ้าอ้อมสำหรับผู้ใหญ่ใช้สำหรับผู้ป่วยใหญ่",
    quantity: 180,
    unit: "แพ็ค",
    category: "CON",
  },
  {
    id: "13",
    code: "CON-003",
    name: "แชมพู",
    description: "แชมพูที่เหมาะกับสภาพผมผู้ป่วย",
    quantity: 30,
    unit: "ขวด",
    category: "CON",
  },
  {
    id: "14",
    code: "CON-004",
    name: "สบู่เหลว / สบู่น้ำเชื้อ",
    description: "สบู่สำหรับความสะอาดระหว่างร่างกาย",
    quantity: 35,
    unit: "ขวด",
    category: "CON",
  },
  {
    id: "15",
    code: "CON-005",
    name: "ผ้ารองกันเปื้อน",
    description: "ผ้ารองป้องกันเครื่องนอนผู้ป่วย",
    quantity: 90,
    unit: "ผืน",
    category: "CON",
  },
  {
    id: "16",
    code: "MED-008",
    name: "เทปแต่งแผล",
    description: "เทปกาวทางการแพทย์สำหรับยึดแผล",
    quantity: 65,
    unit: "ม้วน",
    category: "MED",
  },
  {
    id: "17",
    code: "EQU-004",
    name: "สายยางให้อาหาร",
    description: "สายยางสำหรับให้อาหารเหลวผ่านจมูก",
    quantity: 25,
    unit: "ชิ้น",
    category: "EQU",
  },
  {
    id: "18",
    code: "EQU-005",
    name: "กระบอกฉีดยา",
    description: "กระบอกสำหรับวัดและฉีดยาสารละลาย",
    quantity: 110,
    unit: "ชิ้น",
    category: "EQU",
  },
];

// ── Transaction History ──────────────────────────────────────
export const mockTransactions: Transaction[] = [
  {
    id: "1",
    code: "20251230-001",
    type: "เพิ่มสินค้าใหม่",
    itemCode: "MED-001",
    itemName: "น้ำเกลือ 0.9%",
    quantity: 120,
    operator: "สมหญิง",
    date: "30/12/2568 10:30",
    approvalStatus: "รออนุมัติ",
  },
  {
    id: "2",
    code: "20251230-002",
    type: "เพิ่มสินค้าใหม่",
    itemCode: "MED-002",
    itemName: "น้ำตาลไร้ (น้ำปลอดเชื้อ)",
    quantity: 100,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "รออนุมัติ",
  },
  {
    id: "3",
    code: "20251230-003",
    type: "เพิ่มสินค้าใหม่",
    itemCode: "MED-003",
    itemName: "สายสวนปัสสาวะ",
    quantity: 60,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "รออนุมัติ",
  },
  {
    id: "4",
    code: "20251230-004",
    type: "เพิ่มสินค้าใหม่",
    itemCode: "MED-004",
    itemName: "อุปกรณ์ท่าแมค",
    quantity: 40,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "อนุมัติ",
    approvedBy: "สมหญิง",
    approvedAt: "30/12/2025 12:30",
  },
  {
    id: "5",
    code: "20251230-005",
    type: "เพิ่มสินค้าใหม่",
    itemCode: "MED-005",
    itemName: "ถุงมือแพทย์",
    quantity: 80,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "อนุมัติ",
  },
  {
    id: "6",
    code: "20251230-006",
    type: "เพิ่มสินค้าใหม่",
    itemCode: "MED-006",
    itemName: "หน้ากากอนามัย",
    quantity: 150,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "อนุมัติ",
  },
  {
    id: "7",
    code: "20251230-007",
    type: "เติมสินค้า",
    itemCode: "MED-007",
    itemName: "แอลกอฮอล์",
    quantity: 50,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "อนุมัติ",
  },
  {
    id: "8",
    code: "20251230-008",
    type: "เติมสินค้า",
    itemCode: "EQU-001",
    itemName: "ก๊อซ",
    quantity: 70,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "อนุมัติ",
  },
  {
    id: "9",
    code: "20251230-009",
    type: "เติมสินค้า",
    itemCode: "EQU-002",
    itemName: "คีม",
    quantity: 60,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "อนุมัติ",
  },
  {
    id: "10",
    code: "20251230-010",
    type: "เบิกสินค้า",
    itemCode: "EQU-003",
    itemName: "พลาสเตอร์ปิดแผล",
    quantity: 40,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "ไม่อนุมัติ",
    rejectedBy: "สมหญิง",
    rejectedAt: "30/12/2025 12:30",
    rejectionReason: "สินค้าไม่จำเป็นต้องใช้",
  },
  {
    id: "11",
    code: "20251230-011",
    type: "เบิกสินค้า",
    itemCode: "CON-001",
    itemName: "นม",
    quantity: 200,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "ไม่อนุมัติ",
  },
  {
    id: "12",
    code: "20251230-012",
    type: "เบิกสินค้า",
    itemCode: "CON-002",
    itemName: "แผ่นเฝือ",
    quantity: 180,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "ไม่อนุมัติ",
  },
  {
    id: "13",
    code: "20251230-013",
    type: "เบิกสินค้า",
    itemCode: "CON-003",
    itemName: "แชมพู",
    quantity: 30,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "ไม่อนุมัติ",
  },
  {
    id: "14",
    code: "20251230-014",
    type: "นำออก",
    itemCode: "CON-004",
    itemName: "สบู่เหลว / สบู่น้ำเชื้อ",
    quantity: 35,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "ไม่อนุมัติ",
  },
  {
    id: "15",
    code: "20251230-015",
    type: "นำออก",
    itemCode: "CON-005",
    itemName: "ผ้ารองกันเปื้อน",
    quantity: 90,
    operator: "สมหญิง",
    date: "30/12/2568 11:30",
    approvalStatus: "ไม่อนุมัติ",
  },
  {
    id: "16",
    code: "20260110-001",
    type: "เติมสินค้า",
    itemCode: "MED-001",
    itemName: "น้ำเกลือ 0.9%",
    quantity: 50,
    operator: "วิชัย",
    date: "10/01/2569 09:00",
    approvalStatus: "อนุมัติ",
  },
  {
    id: "17",
    code: "20260110-002",
    type: "เบิกสินค้า",
    itemCode: "MED-006",
    itemName: "หน้ากากอนามัย",
    quantity: 30,
    operator: "กาญจนา",
    date: "10/01/2569 14:00",
    approvalStatus: "รออนุมัติ",
  },
  {
    id: "18",
    code: "20260115-001",
    type: "เพิ่มสินค้าใหม่",
    itemCode: "MED-008",
    itemName: "เทปแต่งแผล",
    quantity: 65,
    operator: "สมหญิง",
    date: "15/01/2569 10:00",
    approvalStatus: "อนุมัติ",
  },
  {
    id: "19",
    code: "20260115-002",
    type: "เพิ่มสินค้าใหม่",
    itemCode: "EQU-004",
    itemName: "สายยางให้อาหาร",
    quantity: 25,
    operator: "วิชัย",
    date: "15/01/2569 11:30",
    approvalStatus: "รออนุมัติ",
  },
  {
    id: "20",
    code: "20260120-001",
    type: "เบิกสินค้า",
    itemCode: "CON-001",
    itemName: "นม",
    quantity: 20,
    operator: "กาญจนา",
    date: "20/01/2569 09:45",
    approvalStatus: "อนุมัติ",
  },
];

export const ITEMS_PER_PAGE = 15;
