import type { Medication, EmergencyContact, EmergencyHospital, ResidentFormState } from "@/types/resident";
export const INITIAL_MEDICATION: Medication = { pdId: "", dmId: "", name: "", dose: "", frequency: "", time: "", mealType: "", note: "" };
export const MEDICATION_MEAL_TYPE_OPTIONS = [
  { value: "before_meal", label: "ก่อนอาหาร" },
  { value: "after_meal", label: "หลังอาหาร" },
];
export const INITIAL_EMERGENCY_CONTACT: EmergencyContact = { name: "", relation: "", phone: "" };
export const INITIAL_EMERGENCY_HOSPITAL: EmergencyHospital = { name: "", phone: "" };

export const INITIAL_FORM_STATE: ResidentFormState = {
  status: "active",
  firstName: "",
  lastName: "",
  nickname: "",
  gender: "",
  dateOfBirth: "",
  idCardNumber: "",
  purpose: "",
  admitDate: "",
  expectedDischargeDate: "",
  roomId: "",
  floor: "",
  profileImage: null,
  profileImagePreview: "",
  chronicDiseases: "",
  chronicDiseasesNote: "",
  medications: [{ ...INITIAL_MEDICATION }],
  surgicalHistory: "",
  drugAllergies: "",
  foodAllergies: "",
  adlScore: "",
  careLevel: "",
  cprStatus: "",
  intakeLabel: "",
  emergencyHospitals: [{ ...INITIAL_EMERGENCY_HOSPITAL }],
  emergencyContacts: [{ ...INITIAL_EMERGENCY_CONTACT }],
};

export const STATUS_OPTIONS = [
  { value: "active",    label: "พักอยู่ในศูนย์" },
  { value: "inactive",  label: "ออกจากศูนย์" },
];

export const GENDER_OPTIONS = [
  { value: "male",   label: "ชาย" },
  { value: "female", label: "หญิง" },
  { value: "other",  label: "อื่นๆ" },
];

export const FLOOR_OPTIONS: Array<{ value: string; label: string }> = [];

export const DEFAULT_MEDICATION_NAME_OPTIONS = [
  { value: "metformin",        label: "Metformin" },
  { value: "amlodipine",       label: "Amlodipine" },
  { value: "atorvastatin",     label: "Atorvastatin" },
  { value: "losartan",         label: "Losartan" },
  { value: "omeprazole",       label: "Omeprazole" },
  { value: "aspirin",          label: "Aspirin" },
  { value: "clopidogrel",      label: "Clopidogrel" },
  { value: "furosemide",       label: "Furosemide" },
  { value: "warfarin",         label: "Warfarin" },
  { value: "glipizide",        label: "Glipizide" },
  { value: "carvedilol",       label: "Carvedilol" },
  { value: "levothyroxine",    label: "Levothyroxine" },
  { value: "prednisolone",     label: "Prednisolone" },
  { value: "enalapril",        label: "Enalapril" },
  { value: "simvastatin",      label: "Simvastatin" },
  { value: "gabapentin",       label: "Gabapentin" },
  { value: "amitriptyline",    label: "Amitriptyline" },
  { value: "digoxin",          label: "Digoxin" },
  { value: "bisoprolol",       label: "Bisoprolol" },
  { value: "spironolactone",   label: "Spironolactone" },
  { value: "hydrochlorothiazide", label: "Hydrochlorothiazide" },
  { value: "isorbide",         label: "Isosorbide dinitrate" },
  { value: "allopurinol",      label: "Allopurinol" },
  { value: "glibenclamide",    label: "Glibenclamide" },
  { value: "insulin",          label: "Insulin" },
  { value: "lisinopril",       label: "Lisinopril" },
  { value: "amlodipine_atorvastatin", label: "Amlodipine/Atorvastatin" },
  { value: "paracetamol",      label: "Paracetamol" },
  { value: "acetaminophen",    label: "Acetaminophen" },
  { value: "tramadol",         label: "Tramadol" },
  { value: "celecoxib",        label: "Celecoxib" },
  { value: "omeprazole_esomprazole", label: "Esomeprazole" },
  { value: "pantoprazole",     label: "Pantoprazole" },
  { value: "rosuvastatin",     label: "Rosuvastatin" },
  { value: "atorvastatin_ezetimibe", label: "Atorvastatin/Ezetimibe" },
  { value: "clonazepam",       label: "Clonazepam" },
  { value: "lorazepam",        label: "Lorazepam" },
  { value: "alprazolam",       label: "Alprazolam" },
  { value: "amoxicillin",      label: "Amoxicillin" },
  { value: "ceftriaxone",      label: "Ceftriaxone" },
  { value: "ciprofloxacin",    label: "Ciprofloxacin" },
  { value: "levofloxacin",     label: "Levofloxacin" },
  { value: "sodium_valproate", label: "Sodium Valproate" },
  { value: "phenytoin",        label: "Phenytoin" },
  { value: "carbamazepine",    label: "Carbamazepine" },
  { value: "ferrous_sulfate",  label: "Ferrous sulfate" },
  { value: "folic_acid",       label: "Folic acid" },
  { value: "vitamin_b12",      label: "Vitamin B12" },
  { value: "calcium",          label: "Calcium" },
  { value: "vitamin_d",        label: "Vitamin D" },
  { value: "potassium",        label: "Potassium" },
  { value: "magnesium",        label: "Magnesium" },
  { value: "zinc",             label: "Zinc" },
  { value: "aspirin_ec", label: "Aspirin EC" },
  { value: "clopidogrel_bisulfate", label: "Clopidogrel Bisulfate" },
  { value: "atorvastatin_calcium", label: "Atorvastatin Calcium" },
  { value: "ezetimibe", label: "Ezetimibe" },
  { value: "pravastatin", label: "Pravastatin" },
  { value: "simvastatin_atorvastatin", label: "Simvastatin/Atorvastatin" },
  { value: "ramipril", label: "Ramipril" },
  { value: "perindopril", label: "Perindopril" },
  { value: "valsartan", label: "Valsartan" },
  { value: "telmisartan", label: "Telmisartan" },
  { value: "irbesartan", label: "Irbesartan" },
  { value: "olmesartan", label: "Olmesartan" },
  { value: "diltiazem", label: "Diltiazem" },
  { value: "verapamil", label: "Verapamil" },
  { value: "nifedipine", label: "Nifedipine" },
  { value: "nicardipine", label: "Nicardipine" },
  { value: "isosorbide_mononitrate", label: "Isosorbide Mononitrate" },
  { value: "isosorbide_dinitrate", label: "Isosorbide Dinitrate" },
  { value: "nitroglycerin", label: "Nitroglycerin" },
  { value: "propranolol", label: "Propranolol" },
  { value: "atenolol", label: "Atenolol" },
  { value: "metoprolol", label: "Metoprolol" },
  { value: "nebivolol", label: "Nebivolol" },
  { value: "amlodipine_besylate", label: "Amlodipine Besylate" },
  { value: "furosemide_spironolactone", label: "Furosemide/Spironolactone" },
  { value: "torsemide", label: "Torsemide" },
  { value: "indapamide", label: "Indapamide" },
  { value: "chlorthalidone", label: "Chlorthalidone" },
  { value: "glimepiride", label: "Glimepiride" },
  { value: "gliclazide", label: "Gliclazide" },
  { value: "sitagliptin", label: "Sitagliptin" },
  { value: "vildagliptin", label: "Vildagliptin" },
  { value: "linagliptin", label: "Linagliptin" },
  { value: "empagliflozin", label: "Empagliflozin" },
  { value: "dapagliflozin", label: "Dapagliflozin" },
  { value: "pioglitazone", label: "Pioglitazone" },
  { value: "rosiglitazone", label: "Rosiglitazone" },
  { value: "liraglutide", label: "Liraglutide" },
  { value: "exenatide", label: "Exenatide" },
  { value: "canagliflozin", label: "Canagliflozin" },
  { value: "glargine", label: "Insulin Glargine" },
  { value: "detemir", label: "Insulin Detemir" },
  { value: "aspart", label: "Insulin Aspart" },
  { value: "lispro", label: "Insulin Lispro" },
  { value: "regular_insulin", label: "Regular Insulin" },
  { value: "NPH_insulin", label: "NPH Insulin" },
  { value: "levetiracetam", label: "Levetiracetam" },
  { value: "topiramate", label: "Topiramate" },
  { value: "lamotrigine", label: "Lamotrigine" },
  { value: "pregabalin", label: "Pregabalin" },
  { value: "memantine", label: "Memantine" },
  { value: "donepezil", label: "Donepezil" },
  { value: "rivastigmine", label: "Rivastigmine" },
  { value: "galantamine", label: "Galantamine" },
  { value: "alendronate", label: "Alendronate" },
  { value: "risedronate", label: "Risedronate" },
  { value: "ibandronate", label: "Ibandronate" },
  { value: "zoledronic_acid", label: "Zoledronic Acid" },
  { value: "calcitonin", label: "Calcitonin" },
  { value: "teriparatide", label: "Teriparatide" },
  { value: "denosumab", label: "Denosumab" },
  { value: "raloxifene", label: "Raloxifene" },
  { value: "estradiol", label: "Estradiol" },
  { value: "conjugated_estrogens", label: "Conjugated Estrogens" },
  { value: "testosterone", label: "Testosterone" },
  { value: "finasteride", label: "Finasteride" },
  { value: "tamsulosin", label: "Tamsulosin" },
  { value: "dutasteride", label: "Dutasteride" },
  { value: "oxybutynin", label: "Oxybutynin" },
  { value: "tolterodine", label: "Tolterodine" },
  { value: "mirabegron", label: "Mirabegron" },
  { value: "sildenafil", label: "Sildenafil" },
  { value: "tadalafil", label: "Tadalafil" },
  { value: "zolpidem", label: "Zolpidem" },
  { value: "zopiclone", label: "Zopiclone" },
  { value: "melatonin", label: "Melatonin" },
  { value: "quetiapine", label: "Quetiapine" },
  { value: "risperidone", label: "Risperidone" },
  { value: "olanzapine", label: "Olanzapine" },
  { value: "haloperidol", label: "Haloperidol" },
  { value: "aripiprazole", label: "Aripiprazole" },
  { value: "sertraline", label: "Sertraline" },
  { value: "escitalopram", label: "Escitalopram" },
  { value: "fluoxetine", label: "Fluoxetine" },
  { value: "paroxetine", label: "Paroxetine" },
  { value: "mirtazapine", label: "Mirtazapine" },
  { value: "venlafaxine", label: "Venlafaxine" },
  { value: "duloxetine", label: "Duloxetine" },
  { value: "bupropion", label: "Bupropion" },
  { value: "trazodone", label: "Trazodone" },
  { value: "amoxicillin_clavulanate", label: "Amoxicillin/Clavulanate" },
  { value: "cefixime", label: "Cefixime" },
  { value: "cephalexin", label: "Cephalexin" },
  { value: "azithromycin", label: "Azithromycin" },
  { value: "clarithromycin", label: "Clarithromycin" },
  { value: "doxycycline", label: "Doxycycline" },
  { value: "clindamycin", label: "Clindamycin" },
  { value: "metronidazole", label: "Metronidazole" },
  { value: "trimethoprim_sulfamethoxazole", label: "Trimethoprim/Sulfamethoxazole" },
  { value: "gentamicin", label: "Gentamicin" },
  { value: "vancomycin", label: "Vancomycin" },
  { value: "linezolid", label: "Linezolid" },
  { value: "rifampicin", label: "Rifampicin" },
  { value: "isoniazid", label: "Isoniazid" },
  { value: "pyrazinamide", label: "Pyrazinamide" },
  { value: "ethambutol", label: "Ethambutol" },
  { value: "acyclovir", label: "Acyclovir" },
  { value: "oseltamivir", label: "Oseltamivir" },
  { value: "valacyclovir", label: "Valacyclovir" },
  { value: "fluconazole", label: "Fluconazole" },
  { value: "itraconazole", label: "Itraconazole" },
  { value: "voriconazole", label: "Voriconazole" },
  { value: "nystatin", label: "Nystatin" },
  { value: "betahistine", label: "Betahistine" },
  { value: "domperidone", label: "Domperidone" },
  { value: "metoclopramide", label: "Metoclopramide" },
  { value: "ondansetron", label: "Ondansetron" },
  { value: "loperamide", label: "Loperamide" },
  { value: "bisacodyl", label: "Bisacodyl" },
  { value: "lactulose", label: "Lactulose" },
  { value: "senna", label: "Senna" },
  { value: "docusate", label: "Docusate" },
  { value: "polyethylene_glycol", label: "Polyethylene Glycol" },
  { value: "sodium_bicarbonate", label: "Sodium Bicarbonate" },
  { value: "potassium_chloride", label: "Potassium Chloride" },
  { value: "magnesium_oxide", label: "Magnesium Oxide" },
  { value: "ferrous_fumarate", label: "Ferrous Fumarate" },
  { value: "cyanocobalamin", label: "Cyanocobalamin (B12)" },
  { value: "thiamine", label: "Thiamine (B1)" },
  { value: "pyridoxine", label: "Pyridoxine (B6)" },
  { value: "ascorbic_acid", label: "Ascorbic Acid (Vitamin C)" },
  { value: "folinic_acid", label: "Folinic Acid" },
];

export const MEDICATION_FREQUENCY_OPTIONS = [
  // --- 1 ครั้ง/วัน (มี 4 กรณี) ---
  { value: "morning", label: "เช้า (1 ครั้ง)" },
  { value: "noon", label: "กลางวัน (1 ครั้ง)" },
  { value: "evening", label: "เย็น (1 ครั้ง)" },
  { value: "bedtime", label: "ก่อนนอน (1 ครั้ง)" },

  // --- 2 ครั้ง/วัน (มี 6 กรณี) ---
  { value: "morning_noon", label: "เช้า/กลางวัน (2 ครั้ง)" },
  { value: "morning_evening", label: "เช้า/เย็น (2 ครั้ง)" },
  { value: "morning_bedtime", label: "เช้า/ก่อนนอน (2 ครั้ง)" },
  { value: "noon_evening", label: "กลางวัน/เย็น (2 ครั้ง)" },
  { value: "noon_bedtime", label: "กลางวัน/ก่อนนอน (2 ครั้ง)" }, 
  { value: "evening_bedtime", label: "เย็น/ก่อนนอน (2 ครั้ง)" }, 

  // --- 3 ครั้ง/วัน (มี 4 กรณี) ---
  { value: "morning_noon_evening", label: "เช้า/กลางวัน/เย็น (3 ครั้ง)" },
  { value: "morning_noon_bedtime", label: "เช้า/กลางวัน/ก่อนนอน (3 ครั้ง)" },
  { value: "morning_evening_bedtime", label: "เช้า/เย็น/ก่อนนอน (3 ครั้ง)" },
  { value: "noon_evening_bedtime", label: "กลางวัน/เย็น/ก่อนนอน (3 ครั้ง)" },

  // --- 4 ครั้ง/วัน (มี 1 กรณี) ---
  { value: "four_times", label: "เช้า/กลางวัน/เย็น/ก่อนนอน (4 ครั้ง)" },
];

export const EMERGENCY_HOSPITAL_MASTERS = [
  { value: "โรงพยาบาลบางมด (Bangmod Hospital)", label: "โรงพยาบาลบางมด (Bangmod Hospital)", phone: "1508" },
  { value: "โรงพยาบาลบางปะกอก 9 อินเตอร์เนชั่นแนล (Bangpakok 9 International Hospital)", label: "โรงพยาบาลบางปะกอก 9 อินเตอร์เนชั่นแนล (Bangpakok 9 International Hospital)", phone: "1745" },
  { value: "โรงพยาบาลบางปะกอก 1 (Bangpakok 1 Hospital)", label: "โรงพยาบาลบางปะกอก 1 (Bangpakok 1 Hospital)", phone: "1745" },
  { value: "โรงพยาบาลราษฎร์บูรณะ (Ratburana Hospital)", label: "โรงพยาบาลราษฎร์บูรณะ (Ratburana Hospital)", phone: "02-872-1001" },
  { value: "โรงพยาบาลนครธน (Nakornthon Hospital)", label: "โรงพยาบาลนครธน (Nakornthon Hospital)", phone: "02-450-9999" },
  { value: "สายด่วนฉุกเฉิน (สพฉ.)", label: "สายด่วนฉุกเฉิน (สพฉ.)", phone: "1669" },
];

  // { value: "prn", label: "เมื่อมีอาการ (PRN)" },
  // { value: "every_4_hours", label: "ทุก 4 ชั่วโมง" },
  // { value: "every_6_hours", label: "ทุก 6 ชั่วโมง" },
  // { value: "every_8_hours", label: "ทุก 8 ชั่วโมง" },
  // { value: "every_12_hours", label: "ทุก 12 ชั่วโมง" },
  // { value: "once_a_week", label: "สัปดาห์ละ 1 ครั้ง" },
